import type { Ticker } from "@/agent/types";

// Top ~50 Robinhood tokenized stocks & ETFs by popularity (Robinhood EU stock tokens).
export const UNIVERSE: Ticker[] = [
  { symbol: "AAPL", name: "Apple", query: "Apple", sector: "Technology" },
  { symbol: "MSFT", name: "Microsoft", query: "Microsoft", sector: "Technology" },
  { symbol: "NVDA", name: "NVIDIA", query: "NVIDIA", sector: "Semiconductors" },
  { symbol: "AMZN", name: "Amazon", query: "Amazon", sector: "Consumer" },
  { symbol: "GOOGL", name: "Alphabet", query: "Alphabet", sector: "Technology" },
  { symbol: "META", name: "Meta Platforms", query: "Meta Platforms", sector: "Technology" },
  { symbol: "TSLA", name: "Tesla", query: "Tesla", sector: "Automotive" },
  { symbol: "AVGO", name: "Broadcom", query: "Broadcom", sector: "Semiconductors" },
  { symbol: "AMD", name: "AMD", query: "AMD semiconductor", sector: "Semiconductors" },
  { symbol: "NFLX", name: "Netflix", query: "Netflix", sector: "Media" },
  { symbol: "PLTR", name: "Palantir", query: "Palantir", sector: "Software" },
  { symbol: "COIN", name: "Coinbase", query: "Coinbase", sector: "Crypto" },
  { symbol: "MSTR", name: "MicroStrategy", query: "MicroStrategy", sector: "Crypto" },
  { symbol: "HOOD", name: "Robinhood", query: "Robinhood Markets", sector: "Fintech" },
  { symbol: "CRM", name: "Salesforce", query: "Salesforce", sector: "Software" },
  { symbol: "ORCL", name: "Oracle", query: "Oracle Corporation", sector: "Software" },
  { symbol: "ADBE", name: "Adobe", query: "Adobe", sector: "Software" },
  { symbol: "INTC", name: "Intel", query: "Intel", sector: "Semiconductors" },
  { symbol: "QCOM", name: "Qualcomm", query: "Qualcomm", sector: "Semiconductors" },
  { symbol: "MU", name: "Micron", query: "Micron Technology", sector: "Semiconductors" },
  { symbol: "TSM", name: "TSMC", query: "TSMC", sector: "Semiconductors" },
  { symbol: "ASML", name: "ASML", query: "ASML", sector: "Semiconductors" },
  { symbol: "IBM", name: "IBM", query: "IBM", sector: "Technology" },
  { symbol: "CSCO", name: "Cisco", query: "Cisco", sector: "Technology" },
  { symbol: "UBER", name: "Uber", query: "Uber", sector: "Consumer" },
  { symbol: "ABNB", name: "Airbnb", query: "Airbnb", sector: "Consumer" },
  { symbol: "SHOP", name: "Shopify", query: "Shopify", sector: "E-commerce" },
  { symbol: "SQ", name: "Block", query: "Block Inc Square", sector: "Fintech" },
  { symbol: "PYPL", name: "PayPal", query: "PayPal", sector: "Fintech" },
  { symbol: "SOFI", name: "SoFi", query: "SoFi", sector: "Fintech" },
  { symbol: "JPM", name: "JPMorgan", query: "JPMorgan", sector: "Banking" },
  { symbol: "BAC", name: "Bank of America", query: "Bank of America", sector: "Banking" },
  { symbol: "GS", name: "Goldman Sachs", query: "Goldman Sachs", sector: "Banking" },
  { symbol: "V", name: "Visa", query: "Visa Inc", sector: "Payments" },
  { symbol: "MA", name: "Mastercard", query: "Mastercard", sector: "Payments" },
  { symbol: "BRK.B", name: "Berkshire Hathaway", query: "Berkshire Hathaway", sector: "Conglomerate" },
  { symbol: "LLY", name: "Eli Lilly", query: "Eli Lilly", sector: "Healthcare" },
  { symbol: "UNH", name: "UnitedHealth", query: "UnitedHealth", sector: "Healthcare" },
  { symbol: "JNJ", name: "Johnson & Johnson", query: "Johnson & Johnson", sector: "Healthcare" },
  { symbol: "PFE", name: "Pfizer", query: "Pfizer", sector: "Healthcare" },
  { symbol: "XOM", name: "ExxonMobil", query: "ExxonMobil", sector: "Energy" },
  { symbol: "CVX", name: "Chevron", query: "Chevron", sector: "Energy" },
  { symbol: "WMT", name: "Walmart", query: "Walmart", sector: "Retail" },
  { symbol: "COST", name: "Costco", query: "Costco", sector: "Retail" },
  { symbol: "HD", name: "Home Depot", query: "Home Depot", sector: "Retail" },
  { symbol: "MCD", name: "McDonald's", query: "McDonald's", sector: "Consumer" },
  { symbol: "KO", name: "Coca-Cola", query: "Coca-Cola", sector: "Consumer" },
  { symbol: "DIS", name: "Disney", query: "Disney", sector: "Media" },
  { symbol: "BA", name: "Boeing", query: "Boeing", sector: "Industrial" },
  { symbol: "GE", name: "GE Aerospace", query: "GE Aerospace", sector: "Industrial" },
  { symbol: "SPY", name: "S&P 500 ETF", query: "S&P 500 stock market", sector: "ETF" },
  { symbol: "QQQ", name: "Nasdaq 100 ETF", query: "Nasdaq 100 tech stocks", sector: "ETF" },
];
